### ISSUE TITLE
Coal bag counter displays 0 when it contains 9

### ISSUE THREAD

**Issue by GryphonIs** [WolffTech/coal-bag-addon#1]
When you have a smithing cape, the counter resets to 0 when you empty it the first time.

I believe this can be fixed if you add an if statement when setting it to 0 that subtracts 27 if the current number is 28 or higher.

**Comment by WolffTech** [comment]
Hmm, It looks like I didn't account for the Cape of Completion for smithing. I also found that the plugin doesn't account for when someone empties the bag, that all the coal might not be removed. The reason is because when the player clicks empty, the counter automatically sets itself to 0, even if there is still coal in the bag. I'll look into different ways to do this and try and push out a update soon.

**Comment by WolffTech** [comment]
Fixed in latest release v1.1 and is now available in the plugin hub.
